# Generated by Django 4.2.6 on 2023-11-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
