# Generated by Django 4.2.6 on 2023-11-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_food', '0002_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
